networks:
  demsausage:
    external: true
services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./mime.types:/etc/nginx/mime.types:ro
      - ../logs/nginx:/var/log/nginx
      - ./content:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - demsausage
